### ISSUE TITLE
Coșul minim de consum

### ISSUE THREAD

**Issue by GabrielMajeri** [GabrielMajeri/somaj-tehnic#3]
Coșul minim de consum este suma minimă de care ai nevoie ca să poți avea un trai decent.

Am putea să comparăm salariul introdus de utilizator cu coșul minim, și să avem un indicator vizual (verde - OK, galben - la limită, roșu - sub trai decent).

Cele mai recente valori sunt din [octombrie 2019](https://www.economica.net/cos-minim-consum-lunar-familie-doi-copii-inflatie-ins-2019-2020_175103.html).

**Comment by BogdanNitica99** [comment]
Am folosit informatii din [acest site](https://www.caleaeuropeana.ro/studiu-friedrich-ebert-stifung-cosul-minim-de-consum-pentru-un-trai-decent-pentru-o-familie-de-doi-adulti-si-doi-copii-s-a-scumpit-la-6-762-lei-lunar-in-2019/).
